version: '2'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"